/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aula05.view;

/**
 *
 * @author jcezarotto
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfEixoX = new javax.swing.JTextField();
        jtfEixoY = new javax.swing.JTextField();
        jBtnAvaliar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCbIncideX = new javax.swing.JCheckBox();
        jCbIncideY = new javax.swing.JCheckBox();
        jCbPrimeiro = new javax.swing.JCheckBox();
        jCbSegundo = new javax.swing.JCheckBox();
        jCbTerceiro = new javax.swing.JCheckBox();
        jCbQuarto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X");

        jLabel2.setText("Eixo Y");

        jtfEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEixoXActionPerformed(evt);
            }
        });

        jtfEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEixoYActionPerformed(evt);
            }
        });

        jBtnAvaliar.setText("Avaliar");

        jLabel3.setText("Posição");

        jCbIncideX.setText("Incide Eixo X");
        jCbIncideX.setEnabled(false);

        jCbIncideY.setText("Incide Eixo Y");
        jCbIncideY.setEnabled(false);
        jCbIncideY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbIncideYActionPerformed(evt);
            }
        });

        jCbPrimeiro.setText("Primeiro Quadrante");
        jCbPrimeiro.setEnabled(false);

        jCbSegundo.setText("Segundo Quadrante");
        jCbSegundo.setEnabled(false);
        jCbSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbSegundoActionPerformed(evt);
            }
        });

        jCbTerceiro.setText("Terceiro Quadrante");
        jCbTerceiro.setEnabled(false);

        jCbQuarto.setText("Quarto Quadrante");
        jCbQuarto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbQuarto)
                            .addComponent(jCbTerceiro)
                            .addComponent(jCbSegundo)
                            .addComponent(jCbPrimeiro)
                            .addComponent(jCbIncideY)
                            .addComponent(jCbIncideX))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEixoX, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEixoY)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jBtnAvaliar)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBtnAvaliar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jCbIncideX)
                .addGap(18, 18, 18)
                .addComponent(jCbIncideY)
                .addGap(18, 18, 18)
                .addComponent(jCbPrimeiro)
                .addGap(18, 18, 18)
                .addComponent(jCbSegundo)
                .addGap(18, 18, 18)
                .addComponent(jCbTerceiro)
                .addGap(18, 18, 18)
                .addComponent(jCbQuarto)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEixoXActionPerformed

    private void jtfEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEixoYActionPerformed

    private void jCbIncideYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbIncideYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbIncideYActionPerformed

    private void jCbSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbSegundoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAvaliar;
    private javax.swing.JCheckBox jCbIncideX;
    private javax.swing.JCheckBox jCbIncideY;
    private javax.swing.JCheckBox jCbPrimeiro;
    private javax.swing.JCheckBox jCbQuarto;
    private javax.swing.JCheckBox jCbSegundo;
    private javax.swing.JCheckBox jCbTerceiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfEixoX;
    private javax.swing.JTextField jtfEixoY;
    // End of variables declaration//GEN-END:variables
}
